// Nosotros podemos arrojar errores con el comando "throw"
// Sint√°xis de throw
// throw <error>

try {
    throw "Error Personalizado"; // <-- Este error no tiene atributos
}
catch(cError){
    console.log("Error: " + cError);
}